### ISSUE TITLE
There should be a unique id. 

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/taxdata#10]
@gofroggyrun and I just discovered that the recid is not unique for CPS records. It would be useful if there were a unique id, whether recid or something else.

**Comment by martinholmer** [comment]
@MattHJensen said:
> @gofroggyrun and I just discovered that the recid is not unique for CPS records. It would be useful if there were a unique id, whether recid or something else.

It is madness to not have a unique key for the records.  There shound never be duplicate ```recid``` values in the ```puf.csv``` file.  Can you have John O'Hare fix this problem as soon as possible.

cc @Amy-Xu

**Comment by Amy-Xu** [comment]
Solved via #11. Closing
