### ISSUE TITLE
Alternatives to CyLp

### ISSUE THREAD

**Issue by andersonfrailey** [open-source-economics/taxdata#104]
Before PR #100 was merged there was some discussion of finding an alternative to CyLp to use in stage 2 of our extrapolation process. @hdoupe and I have talked about this offline as well. I'm opening this issue so we have a place to discuss other open source options we may have.

I did a quick search after lunch, and if there is no opposition to moving away from Python, there is another CLP interface written in Julia, another open source language. I haven't looked too deeply yet, but judging from the [repository](https://github.com/JuliaOpt/Clp.jl), it is a relatively immature project, but a pull request was opened just 13 days ago so there is more activity going on than in CyLp.

I don't have much experience with Julia, but I'm working through the getting started manual and it's relatively easy to pick up the syntax and was built specifically for numerical computing so it's very fast.

I will keep looking for alternatives in my spare time and if others find any I would appreciate them posting them here for discussion. I'm sure there are more options that the one I've posted, possibly in R or another computational language.

@martinholmer @Amy-Xu

**Comment by martinholmer** [comment]
@andersonfrailey and @hdoupe,
Thanks for following up on this which-linear-programming-library-to-use issue.

My main frustration was not being able to install `cylp`, but now I know about easy_install and all is good.  We should probably add that bit of information in the `taxdata/README.md` file.  This is the only "extra" Python package needed to work with the taxdata repo, right?

Never underestimate the value of a package that actually **works**.  There are many packages that are only striving to work, so we should change away from `cylp` only after careful consideration.

@MattHJensen @feenberg @Amy-Xu

**Comment by hdoupe** [comment]
I created a new [branch](https://github.com/hdoupe/taxdata/tree/linprog_experiments) to facilitate testing alternatives to CyLp.  I separated the `solve_lp_for_year` function into a function that prepares `A1`, `A2`, and `b` and a function that takes `A1`, `A2`, `b`, and `tol` and solves for `r` and `s`.

I also looked at writing a solver in Julia (`solve_lp_for_year.jl`).  This doesn't work yet, but if anyone is interested in using Julia for this problem, then they could start from this file.  The IO works, and I wrote what I thought might work for the [JuMP](https://jump.readthedocs.io/en/latest/) solver. 

@andersonfrailey @martinholmer @Amy-Xu

**Comment by andersonfrailey** [comment]
I believe we should reopen discussion on replacing CyLp. I tried to run `stage2.py` yesterday and received this error:
```
Traceback (most recent call last):
  File "stage2.py", line 23, in <module>
    year='2010', tol=0.41)
  File "/Users/andersonfrailey/taxdata/puf_stage2/solve_lp_for_year.py", line 194, in solve_lp_for_year
    LP.objective = c * r + c * s
  File "/Users/andersonfrailey/anaconda/lib/python2.7/site-packages/cylp-0.7.1-py2.7-macosx-10.6-x86_64.egg/cylp/py/modeling/CyLPModel.py", line 949, in objective
    self.objective_ = obj.evaluate()
  File "/Users/andersonfrailey/anaconda/lib/python2.7/site-packages/cylp-0.7.1-py2.7-macosx-10.6-x86_64.egg/cylp/py/modeling/CyLPModel.py", line 266, in evaluate
    cons.perform(token, left, right)
  File "/Users/andersonfrailey/anaconda/lib/python2.7/site-packages/cylp-0.7.1-py2.7-macosx-10.6-x86_64.egg/cylp/py/modeling/CyLPModel.py", line 372, in perform
    if left == None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

@hdoupe also received this error when he tried to run it.

@Amy-Xu, @hdoupe, and myself all spent sometime trying to find a solution today but were unable to.
@hdoupe also tried to install a different version of the package and was unable to.

Both of its dependencies, numpy and scipy, have been updated since we last created a weights file so it's possible one, or both, of those new releases broke it. CyLp was last updated in 2015 so I don't anticipate a fix becoming available anytime soon.

It appears that [the LP-solver in scipy is buggy](https://github.com/scipy/scipy/pull/7123), so I will look for other options over the next few days and see what I can find.

cc: @martinholmer

**Comment by mdhaber** [comment]
@andersonfrailey May I clarify that the _old_ LP-solver in Python, the simplex one, is buggy. I can't guarantee that the new one - the interior point one you referenced - is bug-free, but it does quite well on standard benchmarks. Hopefully it will be pulled soon.

**Comment by martinholmer** [comment]
@andersonfrailey said:
> Both of its dependencies, `numpy` and `scipy`, have been updated since we last created a weights file so it's possible one, or both, of those new releases broke it. CyLp was last updated in 2015 so I don't anticipate a fix becoming available anytime soon.

By all means, look for a replacement.  But in the meantime, you can probably go back (just for your taxdata work) to the earlier numpy, which is the 1.12.1 version.  I would guess everything would work then (because installing the old numpy version will automatically install the older scipy package).

Let me know if you need any help in doing this.

@hdoupe

**Comment by andersonfrailey** [comment]
@mdhaber thanks for the clarification! I will look into using the newer LP-solver as our replacement.

**Comment by hdoupe** [comment]
@mdhaber Nice work on SciPy's LP solver.  I hope it gets merged soon!

**Comment by mdhaber** [comment]
@hdoupe @andersonfrailey Thanks! It really has been ready to go for a while, so I hope it is pulled soon, too. You're welcome to evaluate it before it is pulled, if you'd like. If you don't have a dev setup, here's stand-alone version for use with your existing SciPy install:
https://www.dropbox.com/sh/m7aaq3t2hvncz6h/AACxqAFe44a47nQ_apSMoTasa?dl=0
(I imagine making a GitHub repo for this would be more normal, haha. If you'd prefer that, let me know.)

For a little while, this link will allow you to view the corresponding documentation:
https://circle-artifacts.com/gh/scipy/scipy/3731/artifacts/0/home/ubuntu/scipy/doc/build/html-scipyorg/index.html
I've included the most relevant pages in the folder above, though.

The interface is the same as before, except that `method="interior-point"` doesn't support a callback interface (and I didn't plan on adding it unless it's requested).  Also, there are a ton of new and different options; let me know if you need help navigating them, especially if you don't find the documentation to be clear. 

I hope you find it useful, and I appreciate your feedback!

**Comment by menukaban** [comment]
Hello all, 

I see that the last post made in this thread is August 2017. I wanted to check in if there has been any progress made in finding alternative LP solver since then.

**Comment by andersonfrailey** [comment]
Hi @menukaban, there has been some progress, but nothing conclusive. I've been working with the [PuLP](https://pythonhosted.org/PuLP/index.html) and Scipy packages as well as a few LP solver implementations in Julia to try and find a solution, but haven't settled on anything yet. I opened PR #113 a few months back to show my work with PuLP if you'd like to check that out.

If you have any feedback/ideas for closing this issue we'd love to hear them!

**Comment by martinholmer** [comment]
@andersonfrailey, is there any value in keeping taxdata issue #104 open given your use of PuLP in pull request #200?

**Comment by andersonfrailey** [comment]
No. Closing.
