### ISSUE TITLE
Check tax-unit benefit data (CPS)

### ISSUE THREAD

**Issue by Amy-Xu** [open-source-economics/taxdata#115]
During the development of extrapolation routine for benefit data, Martin spot [this SSI imputation error](https://github.com/open-source-economics/Tax-Calculator/pull/1500#issuecomment-320710036) from the tabulation on participants number per tax unit. It would be great if we could put together a checking routine, or a testing script for this dataset. Due to the lack of official tax-unit benefit statistics, I think we could start brainstorming a checking list and then automate the checking process.  I imagine this is a job parallel to the development of extrapoation routine and hopefully we could get a draft version done before making UBI analysis available to the public on TB.

To this point, I think

- program aggregates (benefit & participation)
- tax unit participation cap

have already proven to be useful and therefore should be included in the list. Would like to hear more suggestions/comments/discussion on this issue. 

@martinholmer @MattHJensen @hdoupe @andersonfrailey

**Comment by MattHJensen** [comment]
I agree that it would be helpful to have an initial version of these tests up and running before we make UBI analysis available to the public on TB. 

@andersonfrailey, could you add it to the grand task list and make the sure necessary responsibilities are accounted for? 


.

**Comment by MattHJensen** [comment]
As for the tables themselves, everything from the C-TAM documentation would probably be valuable to start. Certainly there are other diagnostic histograms that could be valuable as well.

**Comment by Amy-Xu** [comment]
@MattHJensen it wouldn't be difficult to generate those decile tables. Is the goal of these tests to make sure all the benefit numbers stay the same over time? What type of histograms would be good for diagnostic purpose? I assume we couldn't compare tax unit distribution with raw CPS distribution directly.

**Comment by MattHJensen** [comment]
There are a few goals

- Know exactly when and why results change. 
-  Provide up to date tables that summarize the database, allow for diagnostic review, and demonstrate the models capabilities. 
- Provide up to date code for generating useful tables.

**Comment by MattHJensen** [comment]
>What type of histograms would be good for diagnostic purpose?

For example, histograms of participants in a tax unit, like those histograms that helped in the recent [SSI  diagnostic effort](https://github.com/open-source-economics/Tax-Calculator/pull/1500#issuecomment-320710036).

**Comment by Amy-Xu** [comment]
So if there's no objection or further discussion, I'm about to add a regression test script in taxdata repo. This script will generate 1) decile participation and benefit tables for each program, 2) participation and benefit totals, and 3) tabulation of tax-unit participation. Then the script will compare these tables with the existing versions or official stats if available.

@martinholmer @MattHJensen @hdoupe @andersonfrailey

**Comment by MattHJensen** [comment]
Thanks Amy. Sounds great.

**Comment by Amy-Xu** [comment]
Closing this issue as PR #135 addressed the concerns here.
