### ISSUE TITLE
"Array subscript out of range" error for CPS-RETS13V5.sas

### ISSUE THREAD

**Issue by evtedeschi3** [open-source-economics/taxdata#117]
I'm working through the State Database files to rebuild the cps.csv from scratch using the ASEC microdata. Note that I'm using the University Edition of SAS.

The first three SAS scripts -- cpsmar20**.sas -- from NBER work fine. 

For the fourth one -- CPS-RETS13V5.sas -- I get the following error:

`ERROR: Array subscript out of range at line 2203 column 33`

In the log, line 2203 is the %SEARCH2 call

`
2201                                       IF( NUNITS GT 1 )THEN
2202                                               DO;
2203                                                       %SEARCH2
2204                                               END;
`

But in the raw code, it's the TABULATE procedure

`2203                      PROC TABULATE DATA=EXTRACT.CPSRETS&CPSYEAR FORMAT=COMMA12. ;`

It's the only error I get, but the summary table generated has a total of 4 returns in it.

**Comment by MattHJensen** [comment]
cc @andersonfrailey

**Comment by andersonfrailey** [comment]
The "array subscript out of range" error typically occurs when there wasn't enough space allocated in an array. In lines 2033 to 2039 we initiate the array variables used to hold record information:

```SAS
ARRAY PREC(16 , 162) _temporary_ ;	/*	NEW CPS FIELDS	*/
*****
	ANDERSON: NEED TO INCREASE SIZE TREC(*) ARRAY
*****;
ARRAY TREC(16 , 350) _temporary_ ;
ARRAY ICPS(*) ICPS01-ICPS50 ;
ARRAY JCPS(*) JCPS1-JCPS200 ;
```
@evtedeschi3, can you try changing 350 in the TREC array to 400? That should solve the issue.

**Comment by evtedeschi3** [comment]
> @evtedeschi3, can you try changing 350 in the TREC array to 400? That should solve the issue.

Sorry for the delay in getting to this. I am getting the same error message and the same warning about only 4 observations. `The data set EXTRACT.CPSRETS2013 has 4 observations and 352 variables.`

**Comment by andersonfrailey** [comment]
@evtedeschi3, thanks for the update. I'll dig a little more and see if I can come up with a solution.

**Comment by martinholmer** [comment]
@andersonfrailey and @evtedeschi3,  What's the status of taxdata issue #117.
There's been no discussion of this issue since October 23, 2017.

**Comment by evtedeschi3** [comment]
Since (correct me if I'm wrong) the CPS generation script has been migrated over to Python, this issue is moot.

**Comment by martinholmer** [comment]
@evtedeschi3, thanks for the update.  I'll go ahead and close taxdata issue #117.
