### ISSUE TITLE
Add PULINENO for head and spouse

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/taxdata#128]
Add PULINENO for head and spouse to cps records on puf.csv and cps.csv

(Recording in issue form a request from @evtedeschi3)

**Comment by MattHJensen** [comment]
@andersonfrailey, is this something that would be easy to do for the cps.csv file? Would be a big help to some of our users if we could get it out quickly.

**Comment by martinholmer** [comment]
@andersonfrailey, In the rush to update the CPS data files, don't forget to fix the bug in the`cps_weights.csv` file, which is described in [this comment](https://github.com/open-source-economics/taxdata/issues/125#issuecomment-346891030) in issue #125.

**Comment by andersonfrailey** [comment]
This has been taken care of in PR #152. Closing.
