### ISSUE TITLE
Cash and In-Kind Programs in `other_ben`

### ISSUE THREAD

**Issue by andersonfrailey** [open-source-economics/taxdata#148]
Our new intern, @KPinkelman, did some research into which of the programs in `cps_data/benefitprograms.csv` offered cash benefits and which offered in-kind benefits. Here is a table of his results:

Program | Table | Row | 2014_cost | In-Kind or Cash
-- | -- | -- | -- | --
Unemployment Assistance | 11.3 | 16 | 43504 |  
Children's health insurance | 11.3 | 20 | 9317 | In-Kind
Indian health | 11.3 | 22 | 4510 | In-Kind
Health resources and services | 11.3 | 24 | 7604 | In-Kind
Substance abuse and mental health   services | 11.3 | 25 | 3193 | In-Kind
Center for Medicare and Medicaid   Innovation | 11.3 | 27 | 997 | In-Kind
Refundable Premium Tax Credit and Cost   Sharing Reductions | 11.3 | 28 | 13068 | Cash
Other | 11.3 | 30 | 12834 |  
Student assistance--Department of   Education and other | 11.3 | 34 | 56337 | In-Kind
Housing assistance | 11.3 | 36 | 46600 | In-Kind
Child nutrition and special milk programs | 11.3 | 39 | 19490 | In-Kind
Supplemental feeding programs (WIC and   CSFP) | 11.3 | 40 | 6266 | Both
Commodity donations and other | 11.3 | 41 | 823 | In-Kind
Family support payments to States and   TANF | 11.3 | 45 | 20378 | Cash
Low income home energy assistance | 11.3 | 46 | 3537 | In-Kind
Payments to States for daycare assistance | 11.3 | 48 | 5064 | In-Kind
Payments to States--Foster Care/Adoption   Assist. | 11.3 | 50 | 6868 | Cash
Other public assistance | 11.3 | 53 | 1071 |  
Coal miners and black lung benefits | 11.3 | 56 | 426 | Both
Aging services programs | 11.3 | 58 | 1462 | Both
Energy employees compensation fund | 11.3 | 59 | 1052 | Cash
September 11th victim compensation | 11.3 | 60 | 49 | Cash
Refugee assistance and other | 11.3 | 61 | 4403 | Both
351 Farm income stabilization | 3.2 | 42 | 20012 | Cash
352 Agricultural research and services | 3.2 | 43 | 4374 | In-Kind
451 Community development | 3.2 | 62 | 7896 | In-Kind
452 Area and regional development | 3.2 | 63 | 3027 | In-Kind
453 Disaster relief and insurance | 3.2 | 64 | 9747 | Both
506 Social services | 3.2 | 72 | 17299 | Both

And the spreadsheet file for those interested:
[program_types.xlsx](https://github.com/open-source-economics/taxdata/files/1704806/program_types.xlsx)

I told him to leave out Unemployment Assistance because we do not count it in the ultimate calculation of `other_ben`.

A couple of questions remain for our work:
1. How to classify the generic "Other" and "Other Public Assistance" programs
2. How to count programs that are both in-kind and cash programs

cc. @martinholmer

**Comment by martinholmer** [comment]
@Kpinkelman,  you can tabulate a high and low fraction of in-kind benefits in other benefits by doing this:

1. **High fraction** is computed interpreting `Both` as `In-Kind`, and

2. **Low fraction** is computed interpreting `Both` as `Cash.

In both cases be sure to omit unemployment benefits.

Can you post the results of those tabulations in this issue?  Thanks.

**Comment by Kpinkelman** [comment]
@martinholmer , I’m a bit confused as to what you mean by this – My understanding of what you’re asking: 

-	Calculate two values (High fraction and Low fraction) for “other” programs currently left blank (“Other” and “Other public assistance”)

In researching which of these programs offered cash vs in-kind benefits, I looked into how they listed their benefits online. Archives containing information about outlays didn’t detail where the money itself went (either directly to individuals or paying for services). 

To calculate High fraction and Low fraction, where should I draw these numbers from?

**Comment by martinholmer** [comment]
@martinholmer said:
> you can tabulate a high and low fraction of in-kind benefits in other benefits by doing this:
>
> High fraction is computed interpreting Both and <blank> as In-Kind, and
>
> Low fraction is computed interpreting Both and <blank> as Cash.
>
> In both cases be sure to omit unemployment benefits.

Sorry if this wasn't clear.  All I need to know is the range of value of the in-kind fraction for `other_benefits`.
If you had classified each one as either `In-Kind` or `Cash` it would be simple to add up the dollars amounts of all the benefits (other than unemployment compensation) that are labeled `In-Kind` and divide it by the total of all benefits (again omitting unemployment compensation).  Does that make sense?

But above is not the case.  You have two categories that are blank and several others that are labeled `Both`.
All I'm asking is that you tabulate two in-kind fraction estimates.  The first (high) estimate assumes that all the benefits that are blank or `Both` are assumed to be `In-Kind`.  The second (low) estimate assumes that all the benefits that are blank or `Both` are assumed to be `Cash`.  Does that make sense?

**Comment by martinholmer** [comment]
@Kpinkelman ,  Is [this explanation](https://github.com/open-source-economics/taxdata/issues/148#issuecomment-365005709) more clear?

**Comment by martinholmer** [comment]
@Kpinkelman asked:
> To calculate High fraction and Low fraction, where should I draw these numbers from?

From the table shown in the [first comment in this issue](https://github.com/open-source-economics/taxdata/issues/148#issue-295299441).  Didn't you create that table?

**Comment by Kpinkelman** [comment]
@martinholmer, That makes more sense to me. Results below:


| Type        | Estimate   |
| ------------- |:-------------:| 
| Low Fraction (In-Kind/Total) | .52163293 | 
| High Fraction (In-Kind/Total)    | .76352877    |

**Comment by martinholmer** [comment]
@Kpinkelman,  Thanks so much for the range tabulation [here](https://github.com/open-source-economics/taxdata/issues/148#issuecomment-365030750).

I your research can narrow the range that would be great.

@andersonfrailey

**Comment by martinholmer** [comment]
@Kpinkelman answered my question.  Thanks!

**Comment by MaxGhenis** [comment]
@Kpinkelman a couple questions:

1. Do you have the source(s) for this table handy?

2. Is *Family support payments to States and TANF* (currently classified as cash) only the cash component of TANF? As of 2014, TANF was ~25% cash, plus another ~10% tax credits ([per 538](https://fivethirtyeight.com/features/most-welfare-dollars-dont-go-directly-to-poor-people-anymore/)), the rest being in-kind.

3. Is there a rough list of the types of programs included in the two "Other" rows?

**Comment by Kpinkelman** [comment]
@MaxGhenis sorry for the delayed response:

1. The numbers in the table had already been filled out when I received it, but are from budget docs released by the Obama administration (namely, 3.2 and 11.3 on https://obamawhitehouse.archives.gov/omb/budget/Historicals). Unfortunately they don't contain information about how the benefits are administered (in-kind or cash), so that information was mostly gleaned from reading up on descriptions of the programs which likely explains 2.

2. You're likely right here - I'm working on a new version of this table and I'll make sure to change that and double check if any similar mistakes were made with other programs.

3. There isn't currently, but I can look into that and compile a list.

**Comment by Kpinkelman** [comment]
Updated Table: 

Program | Table | Row | 2014_cost | In-Kind or Cash
-- | -- | -- | -- | --
Unemployment Assistance | 11.3 | 16 | 43504 |  
Children's health insurance | 11.3 | 20 | 9317 | In-Kind
Indian health | 11.3 | 22 | 4510 | In-Kind
Health resources and services | 11.3 | 24 | 7604 | In-Kind
Substance abuse and mental health   services | 11.3 | 25 | 3193 | In-Kind
Center for Medicare and Medicaid   Innovation | 11.3 | 27 | 997 | In-Kind
Refundable Premium Tax Credit and Cost   Sharing Reductions | 11.3 | 28 | 13068 | Cash
Other - Medical | 11.3 | 30 | 12834 |  
Student assistance--Department of   Education and other | 11.3 | 34 | 56337 | In-Kind
Housing assistance | 11.3 | 36 | 46600 | In-Kind
Child nutrition and special milk programs | 11.3 | 39 | 19490 | In-Kind
Supplemental feeding programs (WIC and   CSFP) | 11.3 | 40 | 6266 | Both
Commodity donations and other | 11.3 | 41 | 823 | In-Kind
Family support payments to States and   TANF | 11.3 | 45 | 20378 | Both
Low income home energy assistance | 11.3 | 46 | 3537 | In-Kind
Payments to States for daycare assistance | 11.3 | 48 | 5064 | In-Kind
Payments to States--Foster Care/Adoption   Assist. | 11.3 | 50 | 6868 | Cash
Other public assistance | 11.3 | 53 | 1071 |  
Coal miners and black lung benefits | 11.3 | 56 | 426 | Both
Aging services programs | 11.3 | 58 | 1462 | Both
Energy employees compensation fund | 11.3 | 59 | 1052 | Cash
September 11th victim compensation | 11.3 | 60 | 49 | Cash
Refugee assistance and other | 11.3 | 61 | 4403 | Both
351 Farm income stabilization | 3.2 | 42 | 20012 | Cash
352 Agricultural research and services | 3.2 | 43 | 4374 | In-Kind
451 Community development | 3.2 | 62 | 7896 | In-Kind
452 Area and regional development | 3.2 | 63 | 3027 | In-Kind
453 Disaster relief and insurance | 3.2 | 64 | 9747 | Both
506 Social services | 3.2 | 72 | 17299 | Both

Potential Types of Programs in Others - Medical (likely more than this): 

SAMHSA, Inmate healthcare, Federal Refugee Health Promotion Program, Federal Employees Health Benefits Program, Tricare, Healthy Start, etc

Potential Types of Programs in Others - Public Assistance (likely more than this):

Educational assistance, Pell Grants, Head Start, Job Training, Lifeline

**Comment by martinholmer** [comment]
@andersonfrailey,  Is there still something to be discussed in issue #148?
This issue was opened on February 7, 2018, and there has been no discussion in it or reference made to it since March 3, 2018.  If the issue is resolved, you might want to closed it.

**Comment by andersonfrailey** [comment]
I believe we can close this issue now. If anyone involved has further questions they're free to reopen it.

**Comment by MaxGhenis** [comment]
[This spreadsheet](https://docs.google.com/spreadsheets/d/1g_YdFd5idgLL764G0pZBiBnIlnCBGyxBmapXCOZ1OV4) starts with @Kpinkelman's table from https://github.com/PSLmodels/taxdata/issues/148#issuecomment-367119322 and adds a column to exclude benefits that are counted outside `other_ben`. I excluded the following four programs to avoid what I believe would be double-counting:
* *Housing assistance* (`housing_ben`)
* *Unemployment assistance* (`e02300`)
* *Family support payments to States and TANF* (`tanf_ben`)
* *Supplemental feeding programs (WIC and CSFP)* (`wic_ben`)

Based on this, the cash share of `other_ben` [ranges](https://docs.google.com/spreadsheets/d/1g_YdFd5idgLL764G0pZBiBnIlnCBGyxBmapXCOZ1OV4/edit#gid=1185840634) from 17% to 35%, depending on if you consider programs labeled *Both* to be 0% or 100% cash, respectively.
