### ISSUE TITLE
Do imputed benefits include administrative costs?

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/taxdata#153]
Not sure if this belongs in the C-TAM repo or here, as I'm curious about the implementation of benefits in the CPS data.

The [C-TAM README](https://github.com/open-source-economics/C-TAM/blob/master/README.md) says that a 2017 goal is to "Add administrative costs for all welfare programs." The [C-TAM documentation](https://docs.google.com/document/d/1CIfp8KwECJa4bIF9U3hHTf3P7Y19ya2NI5QhEDOyG98/edit) also indicates that administrative totals are used as the source of truth for extrapolating benefits, but I haven't read the whole thing so not sure if the benefits intend to include overhead.

If feasible, both with and without administrative costs would be useful, since without gives value and with gives budget for allocating to replacements like UBI.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> The C-TAM documentation also indicates that administrative totals are used as the source of truth for extrapolating benefits, but I haven't read the whole thing so not sure if the benefits intend to include overhead.

For some reason, the most recent C-TAM documentation (from Sep 2017) has been pending merger since then.
Look at the pull requests for the most up-to-date documentation.  And, yes, this discussion should be in the C-TAM repository.

**Comment by MaxGhenis** [comment]
OK asked in https://github.com/open-source-economics/C-TAM/issues/60.
