### ISSUE TITLE
gzip compression of puf_weights.csv file?

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/taxdata#154]
@andersonfrailey, we have the CPS weights in a compressed file called `cps_weights.csv.gz`, but the PUF weights are in the uncompressed `puf_weights.csv` file, which is almost 25 million bytes in size.

What do you think about also putting the PUF weights in a compressed file named `puf_weights.csv.gz`?

If you don't see any problem with this change, I'll make the necessary Tax-Calculator changes and you can make the necessary taxdata code changes (in preparation for the next PUF data set).

**Comment by andersonfrailey** [comment]
@martinholmer I'm good with this change. I can get a PR that will swap the current weights file with a compressed version and adds a few lines of code to the stage 2 scripts that will compress each time the script is run soon.

**Comment by martinholmer** [comment]
The Tax-Calculator changes are in [pull request 1895](https://github.com/open-source-economics/Tax-Calculator/pull/1895).
