### ISSUE TITLE
Why would n24 exceed nu18?

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/taxdata#157]
My understanding of the Child Tax Credit's [definition of child](https://www.thebalance.com/child-tax-credit-3193009) is that it should be a subset of children under age 18. One criterion is being under age 17, and others limit further within that.

2014 CPS data shows that `n24` and `nu18` have almost identical totals: 78.7M and 78.8M, respectively. Yet `n24` exceeds `nu18` for 9M tax units, 19% of all tax units where `n24>0` ([notebook](http://nbviewer.jupyter.org/github/MaxGhenis/taxcalc-notebooks/blob/master/ctc/nu18_vs_n24.ipynb)). These 9M tax units have 15M total `n24` and 1.3M total `nu18`

Is there a reason I'm missing here, like different residency requirements? If not, should `n24` be capped at `nu18`?

NB: this will become a slightly starker issue after https://github.com/open-source-economics/taxdata/issues/131 is resolved.

**Comment by andersonfrailey** [comment]
@MaxGhenis, I don't have a specific answer for you right now, but I do know we can do a better job calculating n24 in general. I'm wrapping up a few other things right now, but when I finish I'll work on a fix for how we count n24.

**Comment by MaxGhenis** [comment]
Now that https://github.com/open-source-economics/taxdata/issues/131 is resolved, `n24` is no longer capped at 3, and we see CPS data with it as high as 5. This changes some of the metrics I listed in my first comment, using 2014 CPS data ([updated notebook](http://nbviewer.jupyter.org/github/MaxGhenis/taxcalc-notebooks/blob/master/ctc/nu18_vs_n24.ipynb)):
* `n24` totals 81.6M while `nu18` totals 78.8M.
* `n24` exceeds `nu18` for 9.0M tax units, 19.5% of all tax units where n24>0 (tiny change).
* But, these 9.0M tax units now represent a higher 15.7M total `n24` and 1.44M total `nu18`

**Comment by MaxGhenis** [comment]
Updating the [notebook](http://nbviewer.jupyter.org/github/MaxGhenis/taxcalc-notebooks/blob/master/ctc/misc/nu18_vs_n24.ipynb) for taxcalc 0.19.0, where `n24` no longer includes 17-year-olds, shows:

* `n24` totals 76.3M while `nu18` totals 78.6M.
* `n24` exceeds `nu18` for 8.2M tax units, 18.7% of all tax units where `n24>0` (tiny change).
* These 8.2M tax units represent 14.0M total `n24` and 1.2M total `nu18`.

**Comment by martinholmer** [comment]
@MaxGhenis said in taxdata issue #157:
> Updating the notebook for taxcalc 0.19.0, where n24 no longer includes 17-year-olds, shows:
>
>- n24 totals 76.3M while nu18 totals 78.6M.
>- n24 exceeds nu18 for 8.2M tax units, 18.7% of all tax units where n24>0 (tiny change).
>- These 8.2M tax units represent 14.0M total n24 and 1.2M total nu18.

@andersonfrailey,  Why would the CPS values for n24 and nu18 be inconsistent?  
Can you see a way to fix this?  What would be the time schedule for the fix?

**Comment by andersonfrailey** [comment]
>Sorry to see this request move logic from Python to SAS. Is a long-term goal to move everything out of SAS? 

Yes, I'm working on moving everything from SAS to Python ASAP. That is the next big milestone for this repo.

**Comment by martinholmer** [comment]
Issue #157 has been resolved by pull request #183.
