### ISSUE TITLE
Does the CPS data have any college enrollment information?

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/taxdata#160]
Searching the [tc user documentation](http://open-source-economics.github.io/Tax-Calculator/) for education-related keywords, the only inputs I see are `e87521` (AmOppCredit) and `e87530` (lifetime learning), both only in the PUF, and `e03210` (student loan interest) which is in the CPS but I'm guessing don't usually overlap with current enrollment.  [benefitprograms.csv](https://github.com/open-source-economics/taxdata/blob/adfa484bda5dbfbb03dee49bc013c5cac08c5418/cps_data/benefitprograms.csv#L10) has a line for "Student assistance" but I don't see this in the docs, I'm guessing it's in `other_ben`?

Context is that I'm analyzing the [cash transfer plan](https://www.nytimes.com/2018/02/25/books/review/chris-hughes-fair-shot.html) proposed by Chris Hughes, which takes into account full-time college enrollment. Even rough proxies of whether tax units include any full-time students would be helpful. Or is there a way to join this CPS data with other data sources?

**Comment by andersonfrailey** [comment]
We don't include any college enrollment in the CPS file. We've included a few identifying variables in the CPS file that can be used to match tax units back to individuals in the CPS file which includes some information on college enrollment.

**Comment by MaxGhenis** [comment]
Are any examples available of matching back to the CPS file? Is it matching `h_seq` in cps.csv with `XHID` in cps_raw.csv, as mapped in [finalprep.py](https://github.com/open-source-economics/taxdata/blob/master/cps_data/finalprep.py#L61), or are others needed too?

cc @evtedeschi3 as Matt mentioned you've done this.

**Comment by martinholmer** [comment]
No discussion of issue #160 since April 8, 2018, so it would appear this issue is resolved.
