### ISSUE TITLE
Various age fields include end points when names and documentation indicate otherwise

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/taxdata#164]
Documentation and variable name structure for various age fields indicate they should not include the end point. I see four contradictions in the code on this front:

* **`nu05`** includes 5-year-olds based on the [finalprep.py code](https://github.com/open-source-economics/taxdata/blob/801164146006ab9c9b7f8872474b9a6cdec9ada4/cps_data/finalprep.py#L135).
* **`nu13`** includes 13-year-olds based on the [finalprep.py code](https://github.com/open-source-economics/taxdata/blob/801164146006ab9c9b7f8872474b9a6cdec9ada4/cps_data/finalprep.py#L127)
* **`elderly_dependent`** is described as "over 65 years old" in the documentation, but includes 65-year-olds based on the [finalprep.py code](https://github.com/open-source-economics/taxdata/blob/801164146006ab9c9b7f8872474b9a6cdec9ada4/cps_data/finalprep.py#L155). As an aside, it would be helpful if the [user documentation](http://open-source-economics.github.io/Tax-Calculator/) specified the age threshold for this variable.
* **`n24`** has a related issue: only children [*under* age 17](https://www.irs.gov/pub/irs-pdf/p972.pdf) are eligible for the CTC, but [finalprep.py](https://github.com/open-source-economics/taxdata/blob/801164146006ab9c9b7f8872474b9a6cdec9ada4/cps_data/finalprep.py#L145) includes 17-year-olds in `n24`.

`n24` aside, I'm not sure if these are used elsewhere, and how that affects whether the variable names or the logic should be changed.

Relevant links:
* https://github.com/open-source-economics/Tax-Calculator/issues/1669.
* http://open-source-economics.github.io/Tax-Calculator/
* https://github.com/open-source-economics/taxdata/blob/master/cps_data/cps_file_doc.md

**Comment by MaxGhenis** [comment]
A process tweak that could help avoid this is to use exclusively either `<`/`>` or `<=`/`>=` in code. finalprep.py includes endpoints for these variables, but just below them it doesn't with the `f2441` and `EIC` variables.

**Comment by martinholmer** [comment]
@andersonfrailey,
Where do we stand on correcting these bugs in the age variables in the `cps.csv` file?
Are the same kind of errors also present in the `puf.csv` file?

@MattHJensen @MaxGhenis

**Comment by andersonfrailey** [comment]
I'll put together a PR to address these issues today. In the PUF `nu13` and `nu05` include dependents age 13 and 5, so that will need to be updated.

**Comment by MaxGhenis** [comment]
> We then count the number of dependents under 5 and 13 or over 65 years old. 

From https://github.com/open-source-economics/taxdata/blob/master/cps_data/cps_file_doc.md

**Comment by martinholmer** [comment]
@MaxGhenis,  Thanks for pointing out these bugs in the generation of the CPS age variables.
These problems have been fixed in pull request #172.
