### ISSUE TITLE
Can this project upgrade to Python 3.6?

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/taxdata#169]
The Pandas developers seem to be planning to quit supporting Python 2.7 at the end of 2018 as described [here](https://github.com/pandas-dev/pandas/issues/18894).  In the coming months the Tax-Calculator developers would like to transition Tax-Calculator to be a Python 3.6+ project.

**Will this project find it acceptable to have access to only Python 3.6 taxcalc packages?**

**Comment by andersonfrailey** [comment]
@martinholmer asked:
> Will this project find it acceptable to have access to only Python 3.6 taxcalc packages?

Yes. I'm also going to work on updating this project to work with Python 3.6 in the coming months. The only major obstacle is the linear programming model used in stage 2 extrapolation for the PUF. The `CyLP` package we currently use is only compatible with Python 2.7 and it is unlikely that will change anytime soon. My search for a replacement model has taken a backseat to my work on the UBI project, but I'll pick it back up when that is complete.

**Comment by martinholmer** [comment]
@andersonfrailey said:
>> Will this project find it acceptable to have access to only Python 3.6 taxcalc packages?
>
> Yes. I'm also going to work on updating this project to work with Python 3.6 in the coming months. The only major obstacle is the linear programming model used in stage 2 extrapolation for the PUF. The CyLP package we currently use is only compatible with Python 2.7 and it is unlikely that will change anytime soon. My search for a replacement model has taken a backseat to my work on the UBI project, but I'll pick it back up when that is complete.

Thanks for the quick response!
