### ISSUE TITLE
CPS nu18 exceeds ACS by 7% in 2014 (78.8M vs 73.6M)

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/taxdata#171]
See [this notebook](http://nbviewer.jupyter.org/github/MaxGhenis/taxcalc-notebooks/blob/master/exploratory/nu18_n24_acs.ipynb) and [this ACS trend tool](https://census.missouri.edu/acs/trends/report.php?p=29|27|24|21|18|14|11|8|5|3|1&g=01000US&s=Demographic) (I checked it matches the normal ACS data, and CPS trends like [this](https://www.childstats.gov/americaschildren/tables/pop1.asp)). Could this be a weighting issue?

**Comment by andersonfrailey** [comment]
This is probably a multipart issue. First the population growth rates used in stage one probably need updating. Second, we don't target nu18, n24, or any other age related variable during our extrapolation. So while the weights are adjusted to hit primarily income targets, they could be throwing off what you're interested in. A solution would be to add a target for say n24 to the stage two process and see what happens.

Unfortunately, we do not have all of the pieces used to create the weights file for the CPS. PR #145 contains the Fortran code that was used, but not the external files that go along with it.

**Comment by martinholmer** [comment]
**@MaxGhenis (in Tax-Calculator closed issue 1927) said:**

Tax-Calculator's projections for `nu18` (and `n24`, CTC-eligible children) are significantly faster than historical growth and Census projections for children under 18. See [this notebook](http://nbviewer.jupyter.org/github/MaxGhenis/taxcalc-notebooks/blob/master/exploratory/nu18_n24_acs.ipynb) using CPS data. 

For example, tc's 2018 `nu18` estimate is 82.0M vs. 73.8M from Census. By 2025 the difference increases to 15M (90.1M vs 75.0M).

![download 9](https://user-images.githubusercontent.com/6076111/37580081-1ef046fa-2aff-11e8-9507-5ec83f6b2727.png)

**Comment by martinholmer** [comment]
**@MaxGhenis said this on 3/20/2018:**

To confirm then, the high growth rates also result from weights, and not the aging process? tc also projects significantly higher total population growth than the Census does:

![download 10](https://user-images.githubusercontent.com/6076111/37676076-254a9d1c-2c34-11e8-88ed-5f4f6dbc8df2.png)


That's from [this notebook](http://nbviewer.jupyter.org/github/MaxGhenis/taxcalc-notebooks/blob/master/exploratory/pop_proj_tc_vs_census.ipynb) which plots all population totals that can be compared to Census. The difference is least significant for `n21`, but all groups grow faster than Census. Without knowing how the aging process works (is there documentation on that?), it doesn't seem like this would be explained solely by weights.

**Comment by martinholmer** [comment]
@MaxGhenis said in taxdata issue #171:
> To confirm then, the high growth rates also result from weights, and not the aging process?

The values of dollar variables (like earnings) are "aged" from one year to the next using the annual growth factors in the `taxcalc/growfactors.csv` file.

The values of demographic variables (like `XTOT` and `n24`) are **not** changed from year to year, but the weights do change from year to year.  It is the changing weights that makes the total population (the sum of `s006 * XTOT`) rise from year to year.

The weights are constructed in taxdata Stage II as described in [this document](https://github.com/open-source-economics/taxdata/blob/master/doc/Stage1_Stage2_Methodology.pdf).  In that Stage II process, the 2027 total population target is 352.28 million as can be seen in [this file](https://github.com/open-source-economics/taxdata/blob/master/stage1/Stage_II_targets.csv).

But the Stage II weights produce a 2027 population total of 377.53 million as can be seen in the tabulations below or from reading the graph provided by @MaxGhenis above.

@andersonfrailey, do you have a sense of why the actual 2027 population total is so much higher than the target 2027 population total?  377.53 million is **7.2 percent** above 352.28 million.  That's a very large discrepancy for population forecasting over ten-to-fifteen year horizon.

@MattHJensen @Amy-Xu 

Here is the tabulation of the actual 2027 population total:
```
$ tc --version
Tax-Calculator 0.17.0

$ tc cps.csv 2027 --sqldb
You loaded data for 2014.
Tax-Calculator startup automatically extrapolated your data to 2027.
WARNING: Tax-Calculator packages for Python 2.7 will
         no longer be provided beginning in 2019
         because Pandas is stopping development for 2.7.
SOLUTION: upgrade to Python 3.6 now.

$ sqlite3 cps-27-#-#-#.db 
SQLite version 3.20.1 2017-08-24 16:21:36
Enter ".help" for usage hints.
sqlite> select count(*), round(sum(XTOT*s006)*1e-6,2) from dump;
456465|377.53
sqlite> .q

$ 
```

**Comment by MaxGhenis** [comment]
Thanks for the context @martinholmer. I'll direct population aging questions to taxdata and dollar variable aging questions to Tax-Calculator. 

> The values of demographic variables (like XTOT and n24) are not changed from year to year, but the weights do change from year to year.

I'm guessing changing this would be a large endeavor right? I wonder if it will make it hard to address issues like these, also given the fairly significant [decline in household size over time](https://www.statista.com/statistics/183648/average-size-of-households-in-the-us/).

One more chart from the [notebook](http://nbviewer.jupyter.org/github/MaxGhenis/taxcalc-notebooks/blob/master/exploratory/pop_proj_tc_vs_census.ipynb?flush_cache=true): `nu18`, `n1820` and `nu13` (including age 13 until https://github.com/open-source-economics/taxdata/issues/164 is resolved) all  exceed comparable Census projections by 20%+ as of 2027. `nu05` is 9% too low today (also including age 5 for now), though I'm not sure if there are other restrictions on that field.

![download 11](https://user-images.githubusercontent.com/6076111/37685897-72d52c50-2c52-11e8-9192-282724049c40.png)

**Comment by martinholmer** [comment]
@MaxGhenis said:
> Thanks for the context @martinholmer. I'll direct population aging questions to taxdata and dollar variable aging questions to Tax-Calculator.

No.  Tax-Calculator has nothing to do with either "population aging" and "dollar variable aging".  It just **uses** the growfactors and weights supplied by the taxdata repo.  So, if you have question about either, please raise those questions in the taxdata repository.

**Comment by MaxGhenis** [comment]
Here's an update ([notebook](http://nbviewer.jupyter.org/github/MaxGhenis/taxcalc-notebooks/blob/master/exploratory/pop_proj_tc_vs_census.ipynb)) using taxcalc 0.19.0, which removes 17-year-olds from `n24`, 13-year-olds from `nu13`, and 5-year-olds from `nu05` per https://github.com/open-source-economics/taxdata/pull/172 (I made corresponding adjustments to Census projections):

![download 6](https://user-images.githubusercontent.com/6076111/39096807-5e66ba7e-4609-11e8-8556-af5da17464d8.png)

`n24` has the highest difference of these fields:

![download 5](https://user-images.githubusercontent.com/6076111/39096814-67a8f750-4609-11e8-8774-772926065f5f.png)

**Comment by martinholmer** [comment]
@MaxGhenis said in a March 2018 comment in taxdata issue #171:
> [Tax-Calculator] projects significantly higher total population growth than the Census does:
>
>![download 10](https://user-images.githubusercontent.com/6076111/37676076-254a9d1c-2c34-11e8-88ed-5f4f6dbc8df2.png)
>
>That's from [this notebook](http://nbviewer.jupyter.org/github/MaxGhenis/taxcalc-notebooks/blob/master/exploratory/pop_proj_tc_vs_census.ipynb) which plots all population totals that can be compared to Census.

There are two sets of problems with this graph.  First, the CPS input data and weights have changed since March, so now for 2027 the weighted `XTOT` sum is about 363.3 million, which is significantly different from the value shown in the graph (which seems to be about 377 or 378 million).  And second, the Census Bureau projections used in the graph seem to be no longer publicly available.  Certainly, the URL in the linked notebook fails on my computer.  The most recent Census projection I can find is for [2014](https://www.census.gov/data/datasets/2014/demo/popproj/2014-popproj.html), which shows a population total for 2027 of about 352.3 million (which is higher than the 349 million Census projection shown in the graph).  Using the CPS input data on the tip of the master branch and the latest available Census projections for 2027, we have the Tax-Calculator projection of 363.3 million being about 3.1% higher than the Census projection of 352.3 million.

Given all this, I'm removing the "Bug" label from this issue and closing this issue.  If there are remaining issues about the Tax-Calculator population projections implied by the taxdata PUF or CPS data, then they should be raised in new issues that use up-to-date information.

@MattHJensen @feenberg @andersonfrailey @Amy-Xu

**Comment by MaxGhenis** [comment]
The Census took down their 2017 projections due to a calculation error, so I'll check back for them in a few weeks and update the notebook. https://www.census.gov/library/visualizations/2018/comm/century-of-change.html

**Comment by MaxGhenis** [comment]
The Census projections are back, so I updated the comparison with new taxcalc data ([notebook](https://nbviewer.jupyter.org/github/MaxGhenis/taxcalc-notebooks/blob/master/exploratory/pop_proj_tc_vs_census.ipynb)). This shows that taxdata's estimate of `nu18` is 15-20% higher than the Census, and its estimate of `nu05` is about 25% lower than the Census. In general the numbers look closer than before though.
![image](https://user-images.githubusercontent.com/6076111/54415868-e61c8180-46ba-11e9-8dc1-aa9565328d01.png)
![image](https://user-images.githubusercontent.com/6076111/54415946-1a903d80-46bb-11e9-9ccc-ef6ac2a1d380.png)

![image](https://user-images.githubusercontent.com/6076111/54415935-1532f300-46bb-11e9-9e26-202863d7eaf7.png)
