### ISSUE TITLE
Question about capital gains

### ISSUE THREAD

**Issue by jdebacker** [open-source-economics/taxdata#179]
Are capital gains included in the CPS file?  If not, is there an expectation that imputations will be made for this variable?  

Thanks!

**Comment by andersonfrailey** [comment]
@jdebacker, capital gain distributions are in the CPS file as `e01100`, but it is missing net short term and net long term capital gains/losses (`p22250` and `p23250`).

I'm going to look into imputing those variables, but I can't give you a reliable time estimate for the imputations to be ready at this time.

**Comment by jdebacker** [comment]
@andersonfrailey Thanks for this answer.  In the short run, I might provide an arbitrary split in B-Tax, but I look forward to a better imputation.

**Comment by martinholmer** [comment]
The question in issue #179 has been answered and issue #221 discusses an effort to add imputed short-term and long-term capital gains to the CPS data file.
