### ISSUE TITLE
Question about stage 2 targeting

### ISSUE THREAD

**Issue by andersonfrailey** [open-source-economics/taxdata#181]
Here is an example of how we create a target in stage 2 of the PUF extrapolation:
```python
WAGE_1 = (Stage_II_targets[year][target_name] *
              APOPN / AWAGE * 1000 - wage_1.sum())
```

@Amy-Xu, could you explain what the purpose of multiplying the stage 2 target by `APOPN / AWAGE * 1000`? I haven't been able to wrap my head around it.

**Comment by Amy-Xu** [comment]
This is a simplification after some algebra. See the attached for more details. 
<img width="657" alt="screen shot 2018-04-23 at 2 50 11 pm" src="https://user-images.githubusercontent.com/10549597/39146744-a3ba5a66-4705-11e8-8e4b-6cb8e6f83527.png">

r, s, z are exactly what John defined in his documentation. `x_it` is unit-level amount and `X_t` is aggregate amount in year t. The derivation starts with year t's aggregate equals to the weighted summation of year t's unit level amounts, and then plugs in John's definition of each item and stage I factors. The last step divided both sides by `(1+r)/(1+p)` to get the final form of targets.

The targets collected are in thousands, which follows John's example, are converted to actual dollar amounts in calculation. That's where the 1000 comes from.

**Comment by andersonfrailey** [comment]
Makes sense. Thanks, @Amy-Xu!
