### ISSUE TITLE
New puf file issues

### ISSUE THREAD

**Issue by derrickchoe** [open-source-economics/taxdata#209]
@andersonfrailey @MattHJensen @martinholmer @hdoupe 
Hi all,

I hope you're doing well and enjoyed the long weekend. I just downloaded the new puf data file and ran it on one of my notebooks. I noticed that my estimates were off by magnitudes of up to 100%. A quick check with a generic calculator also is giving me unexpected results: taxcalc now predicts that around 67 million tax filers itemized their deductions in 2017 (screenshot attached). I believe that the actual number should be in the mid-40 millions. Is there possibly something going on with the weighting? It's also possible that I'm missing something, and I'm open to suggestions. 

Thanks for your time, and I hope you have a great day.

![image](https://user-images.githubusercontent.com/32269181/40665553-8138ab4a-632b-11e8-9cd1-1e2d0dc29d47.png)

**Comment by andersonfrailey** [comment]
@derrickchoe, are you using the python package downloaded from Conda or the the master branch of the Tax-Calculator repo?

**Comment by derrickchoe** [comment]
@andersonfrailey 
I'm using the version of taxcalc from github. I don't believe I have the conda version downloaded on this machine.
