### ISSUE TITLE
Does the CPS data include refundable state credits, e.g. state EITC?

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/taxdata#227]
A couple questions on refundable state EITCs and CTCs in CPS data:
1. Do any income measures (raw or calculated) in the CPS data include refundable state tax credits?
2. If so, are they specifically identified?

Nothing popped out, and it seems like (2) would require going to the raw CPS, though it's not clear it's there either. A few things I looked at:
* `other_ben`
* `e00700` ("Taxable refunds of state and local income taxes", only in PUF), but since state tax refunds are [usually not taxable](https://ttlc.intuit.com/questions/1899663-do-i-need-to-report-the-state-or-local-refund-i-got-last-year-is-it-taxable), I'd be curious how often they're reported in tax returns.
* [CPS income](https://www.census.gov/cps/data/incdef.html) component 21 is: "State income taxes after all refundable credits (deducted from income)," suggesting it might be in some raw data.

Any insights would be helpful - thank you!

**Comment by andersonfrailey** [comment]
@MaxGhenis there's currently no measure in the CPS data that includes state tax credits.

**Comment by andersonfrailey** [comment]
@MaxGhenis, I don't know of any, but I can keep an eye out for some and will let you know if I find anything.

**Comment by MaxGhenis** [comment]
OK thanks!
