### ISSUE TITLE
How can cps_stage4/extrapolation.py work?

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/taxdata#231]
The benefit `extrapolation.py` script contains this line:
```
 CPS_WEIGHTS_PATH = '../cps_stage2/cps_weights_raw.csv.gz'
```
However, there is no such file in the taxdata repository.
Is this just a typo?  Should the `_raw` be removed?

@hdoupe @andersonfrailey

**Comment by andersonfrailey** [comment]
@martinholmer `cps_weight_raw.csv.gz` was removed in PR #200 and I forgot to update that path. I'll take care of it.

**Comment by hdoupe** [comment]
@andersonfrailey what should the path be?

**Comment by andersonfrailey** [comment]
@hdoupe it should just be `'../cps_stage2/cps_weights.csv.gz'`

**Comment by hdoupe** [comment]
Ok, thanks.

**Comment by martinholmer** [comment]
@andersonfrailey said in issue #231:
> @hdoupe it should just be `../cps_stage2/cps_weights.csv.gz`

This change has been made in PR #233.
