### ISSUE TITLE
CPS records from the same household have the same characteristics

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/taxdata#245]
I stumbled on something fishy, wanted to check whether it's WAI. If you look at CPS records with `h_seq=581`, there are 17, which all have `ffpos=1`. 15 of these 17 (`RECID` 986-1000) have many identical characteristics:
* `age_head=47` 
* `age_spouse=39`
* `s006=13`
* `e00200=0`
* `XTOT=6`

etc., though they differ on some like `e00900p` and `agi_bin`. I didn't check if this is broadly common across tax units with the same `h_seq`, but this seems to suggest that some of the same people are being put into multiple tax units. Is this intended? The [CPS file documentation](https://github.com/open-source-economics/taxdata/blob/master/cps_data/cps_file_doc.md) doesn't seem like it would produce this result:

> Households with multiple families or children who also report income are slightly more complicated. In these cases, an initial tax unit is created using the head of the household. The algorithm then loops through the remaining members of the household to determine if they are part of the first tax unit. If they are, their information is added as either a spouse or dependent to the head of the household. If they are not, or are deemed to be a dependent who must also file a return, a new tax unit is constructed for that person. The search for a spouse and dependents is repeated, unless they are a dependent filer themselves. Ultimately, all individuals in the household will be assigned to a tax unit.

**Comment by andersonfrailey** [comment]
@MaxGhenis, this is probably due to our approach to adjusting for top coding. When we have a record that has been top coded for whatever reason, we create copies of that record each with slightly different values for just the top coded variable.

It doesn't look like this specific record has a wage top code, but it might have one for interest, dividends, etc.

**Comment by MaxGhenis** [comment]
Ah OK, thanks!
