### ISSUE TITLE
Remove vet_ben from calculation of other_ben

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/taxdata#277]
Per https://github.com/open-source-economics/C-TAM/issues/68#issuecomment-413300566:
>Given VB can be so high due to pensions, which we'd expect would be unrelated to other benefits, would it make sense to drop that and just consider Medicaid, SSI, and SNAP (maybe something like WIC too)? It doesn't look like any of the other_ben programs relate to veterans.

@andersonfrailey and @MattHJensen agreed.

This involves removing the `vet_ben` part of https://github.com/open-source-economics/taxdata/blob/master/cps_data/finalprep.py#L367.

**Comment by martinholmer** [comment]
The merge of pull request #278 by @andersonfrailey resolves issue #277.
