### ISSUE TITLE
Translate CPS-PUF match to Python

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/taxdata#31]
The CPS-PUF matching scripts are currently written in SAS and reside in https://github.com/open-source-economics/cps-puf. These should be translated into Python and incorporated into this repository.

**Comment by martinholmer** [comment]
@andersonfrailey,  Where do we stand on taxdata issue #31?  Hasn't all this been done?  If so, it makes sense to add a comment describing what has been done to resolve issue #31, and then close issue #31.

@MattHJensen @Amy-Xu

**Comment by andersonfrailey** [comment]
@martinholmer this is a work in progress. We recently brought on an intern who is SAS certified and knows some Python so she is familiarizing herself with the matching scripts and will work with me to get them all translated.

**Comment by martinholmer** [comment]
@andersonfrailey, Thanks for the quick and informative update on taxdata issue #31.  We'll keep this issue open.

**Comment by andersonfrailey** [comment]
The translation of the match files from SAS to Python is complete so I am closing this issue.
