### ISSUE TITLE
Create private conda package for each PUF file

### ISSUE THREAD

**Issue by PeterDSteinberg** [open-source-economics/taxdata#44]
It has become tough to remember which version of the PUF goes with which version(s) of OG-USA, Tax-Calc, B-Tax and it has also limited automation. 

Fix: 

* [x] Make a private conda package <strike>`ospc-puf` </strike> `taxpuf`, then versions of that package for each `puf.csv.gz` we have used.  
* [x] Keep <strike>`ospc-puf`</strike> `taxpuf` in this organization
https://anaconda.org/opensourcepolicycenter/
* [x] Make a new version of <strike>`ospc-puf`</strike> `taxpuf` each time a new `puf.csv` is made
* [ ] In the OG-USA, Tax-Calc, B-Tax repos be sure that the `conda.recipes/meta.yaml` names specific versions of the `ospc-puf` package to install.

**Comment by martinholmer** [comment]
The creation of the private taxpuf repository resolves taxdata issue #44, right? Unless somebody corrects my understanding, I'll close this issue on Monday, Feb 6th.

@andersonfrailey @MattHJensen @Amy-Xu @PeterDSteinberg

**Comment by martinholmer** [comment]
@PeterDSteinberg, The creation of the private taxpuf repository resolves taxdata issue #44, right?
Can you confirm this?

**Comment by PeterDSteinberg** [comment]
This issue is resolved.  Note the 4th bullet item in my first comment will not be done, at least not at this point.
