### ISSUE TITLE
Where in taxdata repo is program that writes WEIGHTS.csv file?

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/taxdata#55]
@andersonfrailey,  Which program writes the final version of the `WEIGHTS.csv` file?

**Comment by andersonfrailey** [comment]
@martinholmer it is [CLP_solver_16Years.py](https://github.com/open-source-economics/taxdata/blob/master/Stage%20II/CLP_solver_16Years.py)

**Comment by martinholmer** [comment]
@andersonfrailey,  Thanks for the pointer to the code that generates the `WEIGHTS.csv` file.
Here are the last two statements of that Python program:
```
# Export all weights
z = df(z, columns=['WT2009','WT2010','WT2011','WT2012','WT2013','WT2014',
                   'WT2015','WT2016','WT2017','WT2018','WT2019','WT2020',
                   'WT2021','WT2022','WT2023','WT2024', 'WT2025', 'WT2026'])
z.to_csv('WEIGHTS.csv', index = False)
```
I think we need to insert the following statement between these two existing statements:
```
z = z.round(0).astype('int64')
```
I think that will round the weights to the nearest whole number and then convert them to an integer datatype, so that the z.to_csv() call will write a CSV file containing integers.

Can you check that this suggest works as I imagine it will?  If it does, can you prepare a taxdata pull request that makes this change?  And then can you prepare a tax-calculator pull request that replaces the old float weights with the new integer weights?   Doing all this will improve things along the lines discussed in [tax-calculator pull request 1153](https://github.com/open-source-economics/Tax-Calculator/pull/1153), which will not be needed after you make these changes.

@MattHJensen @Amy-Xu
