### ISSUE TITLE
Should the CPS-PUF matching scripts available in TaxData?

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/taxdata#77]
My instinct is that the SAS scripts for the CPS-PUF match should be in TaxData. Once the Python scripts are available, they can replace the SAS scripts. Any reason not to keep them here? 

cc @andersonfrailey @martinholmer @Amy-Xu

**Comment by Amy-Xu** [comment]
I have no clue.

**Comment by martinholmer** [comment]
@MattHJensen said:
> My instinct is that the SAS scripts for the CPS-PUF match should be in TaxData. Once the Python scripts are available, they can replace the SAS scripts. Any reason not to keep them here?

Sounds like a reasonable plan.  Where are those SAS scripts now?

@andersonfrailey @Amy-Xu

**Comment by andersonfrailey** [comment]
This is reasonable to me. I can upload them now.

**Comment by martinholmer** [comment]
taxdata issue #77 was resolved by the merger of taxdata pull request #78, which was contributed by @andersonfrailey.
