### ISSUE TITLE
Progress on fixing spouse ages in SAS code

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/taxdata#89]
@andersonfrailey said on March 29, 2017:
> Thanks for the work on this, @martinholmer. Julia, our intern, discovered a bug in the original SAS code that caused the spouse to be misidentified when creating some of the CPS tax units, which could explain some of the major disparities in age we have been seeing.
>
> She found a fix for it and I will work on evaluating the results before the next PUF release.

@andersonfrailey,  Can you provide us with a progress report on the work you and Julia are doing?

**Comment by andersonfrailey** [comment]
Julia and I have been working on getting all of the SAS code used in the matching process translated into python and while doing so have found a few bugs to fix including the one mentioned above. I haven't had the oportunity to do a full evaluation of the results, but I've recently talked to Julia about it and her initial assesment is the fixes she proposed solve most of the age issues.

I would estimate that we're about 60% done with the project.

**Comment by martinholmer** [comment]
@andersonfrailey,  Thanks for the progress report.

**Comment by andersonfrailey** [comment]
Each of the SAS files is now translated, but there are still bugs being ironed out. I don't want to open a PR here until we can get everything running correctly, so [here](https://github.com/andersonfrailey/StatMatch) is a link to the repo I set up on my personal account to work on the translation if you're interested in following along.

Now that @hdoupe has started, he'll be helping me get everything up and running. As soon as it's all working we'll open up a PR here.

@martinholmer @MattHJensen @Amy-Xu

**Comment by martinholmer** [comment]
taxdata issue #89 has been resolved by pull request #100 as described in issue #92.
