### ISSUE TITLE
facilitate user feedback and understanding of the database by publishing summary stats

### ISSUE THREAD

**Issue by MattHJensen** [open-source-economics/taxdata#9]
The extrapolation routine is somewhat difficult for outsiders to dig into right now. The methodology is daunting and you can't interact with the extrapolation routines without the PUF. 

I think we could make it much easier for people to understand the data behind TaxBrain if we published a table with summary statistics of every variable for every year. 

Here are the columns that come to mind. 

```
year
e-code
English_description
weighted_sum
weighted_mean
count_pos
sum_pos   
count_neg
sum_neg
sum_agi_dec1
sum_agi_dec2
sum_agi_dec3
sum_agi_dec4
sum_agi_dec5
sum_agi_dec6
sum_agi_dec7
sum_agi_dec8
sum_agi_dec9
sum_agi_dec10
```

Do others think that this would be useful? If so, are these the right columns? If not, what would be more helpful to allow users to understand the data?

cc @feenberg, @martinholmer, @Amy-Xu, @johnfohare, @aviard

**Comment by MattHJensen** [comment]
I just edited the previous comment to add sums by agi decile. One way to think of this might be to ask ourselves the question "what information would be useful for us to receive from JCT?" We should publish anything that we think would be useful for them to publish.

**Comment by feenberg** [comment]
On Fri, 30 Oct 2015, Matt Jensen wrote:

> 
> The extrapolation routine is somewhat difficult for outsiders to dig into right now.
> The methodology is daunting and you can't interact with the extrapolation routines
> without the PUF.
> 
> I think we could make it much easier for people to understand the data behind TaxBrain
> if we published a table with summary statistics of every variable for every year.
> 
> Here are the columns that come to mind.
> 
> year
> e-code
> English_description
> weighted_sum
> weighted_mean
> count_pos
> sum_pos 
> count_neg
> sum_neg
> 
> Do others think that this would be useful? If so, are these the right columns? If not,
> what would be more helpful to allow users to understand the data?

Wouldn't the sum be enough? That gives a table of about 150 rows and 10 
columns (one colum for each year). There are very few variables that are 
allowed to be negative.

dan

**Comment by feenberg** [comment]
On Fri, 30 Oct 2015, Matt Jensen wrote:

> 
> I just edited the previous comment to add sums by agi decile. One way to think of this
> might be to ask ourselves the question "what information would be useful for us to
> receive from JCT?" We should publish anything that we think would be useful for them
> to publish.
>

Estimates of wages and capital gains - cg is especially important since it 
is taxed at a different rate.

dan

**Comment by MattHJensen** [comment]
@feenberg said: 

> Wouldn't the sum be enough?

So now I am thinking of a panel that is 2400 (16 years * ~150 vars) long and 14 columns wide. 

The years would be 2009 - 2024

The twelve columns would be:

```
year
e-code 
English description
sum
sum_agi_dec1
sum_agi_dec2
sum_agi_dec3
sum_agi_dec4
sum_agi_dec5
sum_agi_dec6
sum_agi_dec7
sum_agi_dec8
sum_agi_dec9
sum_agi_dec10
```
The smaller table that Dan described of of only sums (150 columns and 16 years) would also likely be useful.

**Comment by Amy-Xu** [comment]
The columns sound reasonable to me, but do we need to give all 150 variable to users? Many of them would be sharing one blow-up factor, and we probably end up giving a lot of redundant information that users might need to dig into the giant table to find what they need.

**Comment by martinholmer** [comment]
@MattHJensen, You raised taxdata issue #9 on "publishing summary stats" about 15 months ago.
Hasn't this issue been resolved by the tabulations @Amy-Xu added to the Tax-Calculator repo some time ago?

**Comment by martinholmer** [comment]
taxdata issue #9 was resolved by a series of Tax-Calculator enhancements contributed by @Amy-Xu.  So, taxdata issue #9 is being closed.
