### ISSUE TITLE
Preparing a new puf.csv file

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/taxdata#95]
There are several enhancements nearing completion that need to be finished before we can issue a new version of the `puf.csv` file.  Coordinating these separate enhancements --- so that there is just one new `puf.csv` file incorporating all the enhancements --- will minimize the disruption in projects that use the `puf.csv` file.  Here are the separate enhancements:

- prepare the raw `cps-matched-puf.csv` file using Python scripts rather than SAS scripts (@andersonfrailey in issue #92 and PR #xx)

- remove *ad hoc* age-difference logic from `puf_data/finalprep.py` now that the new `cps-matched-puf.csv` file has more sensible ages for taxpayer and spouse (@martinholmer in PR #yy)

- add nu18 variable (@hdoupe in PR #93)

- replace net casualty losses with gross casualty losses (@martinholmer in PR #94)

In addition, PR #93 and PR #94 will require changes in Tax-Calculator, which I will be happy to handle.

Is there anything else?  Does this coordination seem worth the benefit in less disruption?

@MattHJensen @Amy-Xu @andersonfrailey @hdoupe

**Comment by MattHJensen** [comment]
The [request that requires nu18](https://github.com/open-source-economics/Tax-Calculator/issues/1409) was for the new capability on TaxBrain by the 20th. It seems very unlikely that can be accomplished if we bundle it with all of these other changes, and even if it could be accomplished by rushing, I don't think we should rush the adoption of the new puf.csv file. 

That said, it only makes sense not to bundle #93 if we think it could be on TaxBrain by (or near) the 20th if we proceed with it first. Unless there is a shortcut I am missing, that would require:

1. Merging #93 here. 
2. Releasing a new taxpuf
3. Merging a forthcoming PR to tax-calculator
4. Releasing a new taxcalc (0.9.0, probably)
5. Creating a new conda package
6. Testing the new taxpuf and new taxcalc against other projects
7. Fixing outstanding compatibility issues w/ latest version of taxcalc and any new ones. 
8. Deploying to TaxBrain. 

I am going to ask the requester whether the 20th was a hard deadline or a soft deadline. If it is a hard deadline, I think we should assume we can't make it. If it is a soft deadline, I think we should try to make it and potentially miss by a few days.

**Comment by martinholmer** [comment]
@MattHJensen said:
> That said, it only makes sense not to bundle #93 if we think it could be on TaxBrain by (or near) the 20th.

How likely is that?  TaxBrain is still using **0.8.3** from May 1st, rather than 0.8.4 or the most recent 0.8.5 from June 8th.

**Comment by MattHJensen** [comment]
> How likely is that? 

I will get in touch with @PeterDSteinberg as well as the enhancement requester to see whether he and other webapp-public contributors have bandwidth later this week / early next week to work on deployment

> TaxBrain is still using 0.8.3 from May 1st, rather than 0.8.4 or the most recent 0.8.5 from June 8th.

We can skip over taxcalc releases for TaxBrain, so the fact that we are a few releases behind shouldn't slow us down.

**Comment by MattHJensen** [comment]
> I will get in touch with @PeterDSteinberg as well as the enhancement requester to see whether he and other webapp-public contributors have bandwidth later this week / early next week to work on deployment

@PeterDSteinberg thinks next Tuesday is a reasonable goal _if_ we have the taxcalc and taxpuf releases by eod Thursday.

**Comment by martinholmer** [comment]
@MattHJensen said:
>> TaxBrain is still using 0.8.3 from May 1st, rather than 0.8.4 or the most recent 0.8.5 from June 8th.
>
> We can skip over taxcalc releases for TaxBrain, so the fact that we are a few releases behind shouldn't slow us down.

I interpreted TaxBrain being stuck on 0.8.3 as an indication that the code was being changed so much (for example, [webapp-public pull request 556](https://github.com/OpenSourcePolicyCenter/webapp-public/pull/556)) that it was not possible to upgrade TaxBrain to 0.8.4 or 0.8.5.  Otherwise, why weren't those upgrades done?

**Comment by MattHJensen** [comment]
> I interpreted TaxBrain being stuck on 0.8.3 as an indication that the code was being changed so much (for example, webapp-public pull request 556) that it was not possible to upgrade TaxBrain to 0.8.4 or 0.8.5.

That's not quite right. More accurately, the pause in releases was to give the webapp-public team time to make progress on, for example, 556, rather than dealing with the releases. We did attempt a 0.8.4 release, but we thought  https://github.com/open-source-economics/Tax-Calculator/issues/1367 was blocking it and that it would make more sense to wait until you were back from vacation. Anyways, the short answer to why we haven't upgraded to 0.8.4 and 0.8.5 is: resource budgeting.

**Comment by martinholmer** [comment]
Closing issue #95 as it has been replaced by issue #96.
